name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'

  build:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
  deploy:
    name: Deploy to GoDaddy
    runs-on: ubuntu-latest

    needs: build

    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to GoDaddy
        run: |
          ssh -oHostKeyAlgorithms=+ssh-rsa tf5t3ny7mdk2@68.178.244.11 "cd /home/tf5t3ny7mdk2/public_html && git pull origin main"